---
title: "Tidy Tuesday 27/08/2019"
output:
  github_document: 
    df_print: kable
always_allow_html: yes
---

```{r opts, echo = FALSE}
figs_path <- paste0(here::here("docs", "assets", "images"),"/")
knitr::opts_chunk$set(
  fig.path = figs_path
)
```

# Data description

From From [TidyTuesdays github](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-08-27):

> This week's data is from Wikipedia, by way of Andrew Collier.

# Import data and packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(Cairo)

simpsons <- readr::read_delim("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-27/simpsons-guests.csv", delim = "|", quote = "")

```

# Data 

```{r}
glimpse(simpsons)
```

# Looking ate the roles

```{r message=FALSE, warning=FALSE}
simpsons %>% 
  select(role) %>% 
  top_n(15)
```

Sometimes that's more than one role for guest in one episode. Let's split this.

```{r simg_freq, message=FALSE, warning=FALSE, dev='CairoPNG'}
simpsons %>% 
  separate_rows(role, sep = ";\\s*") %>% 
  select(season, role) %>% 
  filter(season != "Movie") %>% 
  mutate(type_guest = case_when(
    str_detect(role, regex('^Sings', ignore_case = TRUE)) ~ "Sings",
    str_detect(role, regex('voice', ignore_case = TRUE)) ~ "Voice",
    str_detect(role, regex('himself|herself|themselves', ignore_case = TRUE)) ~ "Themselves",
    str_detect(role, regex('narrator', ignore_case = TRUE)) ~ "Narrator",
    TRUE ~ "Character"
    ),
    season = as.numeric(season)
    ) %>% 
  ggplot(aes(season, 
             color = factor(type_guest,
                            levels = c("Character", "Themselves", "Sings",
                                       "Narrator", "Voice")))) + 
  geom_freqpoly() + 
  labs(x = "Season",
       y = "Count",
       title = "Which do guests play more each season of the Simpsons?",
       subtitle = "They usually play non-singing characters or themselves",
       color = "Type of Guest") + 
  scale_colour_brewer(palette = 'Dark2') +
  theme_classic() +
  theme(
        title = element_text(colour = "darkslategrey"),
        legend.text = element_text(colour = "darkslategrey"),
        axis.ticks = element_line(color = 'lightslategrey'),
        axis.text = element_text(color = 'lightslategrey'),
        axis.line = element_blank()
        )
```

